name: Configure and make

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.2.Rel1'
    - name: configure
      run: ./configure CFLAGS='-Wall -Werror -g'
    - name: make
      run: make

  memory_test:
    name: Memory test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run memory test and check return code
      run: |
        ./memory_test
        if [ $? -ne 0 ]; then
          echo "Memory test failed!"
          exit 1
        fi

    
